# Site settings
title: Mahesh Man Singh
tagline: Politician
description: > # this means to ignore newlines until "baseurl:"
        The Official homepage of Nepali Congress Leader - Mahesh Man Singh.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maheshmansingh.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Collections
# Add new slides as HTML files inside the _panels folder
collections:
  - panels
